### ISSUE TITLE
Collect data for all 5 countries to include in the app

### ISSUE THREAD

**Issue by MartaBekyarska** [kodiri/seasonal-cuisine#4]
1. Find information how Bulgaria, Romania, China, Trinidad and Tobago celebrate Christmas. For Pakistan how people celebrate Eid. 
2. Find out what food is prepared for these festivals.
3. Find images related to these festivals.

Useful links: 
- https://www.thespruceeats.com/bulgarian-christmas-recipes-1135377
- https://www.pexels.com/search/christmas%20food/
- https://unsplash.com/search/photos/christmas-food
- https://www.canva.com/photos/free/?query=christas%20food

**Comment by bean720** [comment]
Have got the bulk of 4 countries ready, Trinidad & Tobago to go. Please see attached file. 
[Food App.xlsx](https://github.com/kodiri/seasonal-cuisine/files/2653630/Food.App.xlsx)

**Comment by bean720** [comment]
Need to know what format the items are being used in your dummy data so I can translate the raw research into item/object/array based on your preferences.

**Comment by MartaBekyarska** [comment]
Please fetch the latest update of the app. See the data model and check the properties for every recipe.
